INSERT INTO modules (name) VALUES ('Kreatywne pomysły na spędzanie czasu z rodziną')
INSERT INTO modules (name) VALUES ('Jak lepiej zarządzać swoim czasem')
INSERT INTO modules (name) VALUES ('Jak tworzyć kampanie reklamowe które przyciągają klientów')
INSERT INTO modules (name) VALUES ('Planowanie budżetu domowego prosty przewodnik')
INSERT INTO modules (name) VALUES ('Od porażki do sukcesu lekcje które zmieniają życie')
INSERT INTO modules (name) VALUES ('Jak znaleźć swoją pasję i żyć pełnią życia')
INSERT INTO modules (name) VALUES ('Social Media Marketing Jak zwiększyć zasięgi organiczne')
INSERT INTO modules (name) VALUES ('Content marketing od pomysłu do publikacji')
INSERT INTO modules (name) VALUES ('Sztuka małych kroków jak wprowadzać zmiany na lepsze')
INSERT INTO modules (name) VALUES ('Zrównoważony rozwój w biznesie Od wizji do działania')
INSERT INTO modules (name) VALUES ('Jak być szczęśliwym na co dzień')
INSERT INTO modules (name) VALUES ('Kreatywność w biznesie Jak przełamać schematy myślenia')
INSERT INTO modules (name) VALUES ('Sztuka pisania jak stworzyć pierwszą książkę')
INSERT INTO modules (name) VALUES ('Fotografia dla początkujących Od teorii do praktyki')
INSERT INTO modules (name) VALUES ('Podróż w głąb siebie odkrywanie swoich wartości')
INSERT INTO modules (name) VALUES ('Zero waste praktyczne porady na start')
INSERT INTO modules (name) VALUES ('Inspiracja w codziennym życiu jak znaleźć swoje źródło pomysłów')
INSERT INTO modules (name) VALUES ('Miasta przyszłości Jak będą wyglądać za 50 lat')
INSERT INTO modules (name) VALUES ('Równowaga między pracą a rodziną Czy to możliwe')
INSERT INTO modules (name) VALUES ('Historie sukcesu które inspirują do działania')
INSERT INTO modules (name) VALUES ('Jak ograniczyć ślad węglowy w codziennym życiu')
INSERT INTO modules (name) VALUES ('Analiza danych marketingowych jak podejmować lepsze decyzje')
INSERT INTO modules (name) VALUES ('Pokonaj swoje lęki i osiągnij więcej')
INSERT INTO modules (name) VALUES ('Odnawialne źródła energii jak wykorzystać je w domu')
INSERT INTO modules (name) VALUES ('Efektywne sposoby na organizację rodzinnego życia')
INSERT INTO modules (name) VALUES ('DIY Jak tworzyć własne dekoracje i oszczędzać pieniądze')
INSERT INTO modules (name) VALUES ('Tworzenie atrakcyjnych ofert sprzedażowych')
INSERT INTO modules (name) VALUES ('Podstawy rysunku jak zacząć swoją przygodę ze sztuką')
INSERT INTO modules (name) VALUES ('Email marketing który sprzedaje praktyczne wskazówki')
INSERT INTO modules (name) VALUES ('Jak wychować pewne siebie dziecko')
INSERT INTO modules (name) VALUES ('Marzenia a cele jak przekształcić pragnienia w rzeczywistość')
INSERT INTO modules (name) VALUES ('Storytelling wizualny Jak tworzyć opowieści obrazem')
INSERT INTO modules (name) VALUES ('SEO w pigułce jak zwiększyć widoczność swojej strony')
INSERT INTO modules (name) VALUES ('Jak edukować dzieci o ochronie środowiska')
INSERT INTO modules (name) VALUES ('Budowanie zaangażowanej społeczności online')
INSERT INTO modules (name) VALUES ('Moda ekologiczna jak wybierać odpowiedzialnie')
INSERT INTO modules (name) VALUES ('Jak zaprojektować idealne wnętrze swojego domu')
INSERT INTO modules (name) VALUES ('Nowoczesne technologie wspierające ekologię')
INSERT INTO modules (name) VALUES ('Tworzenie muzyki Prosty przewodnik dla początkujących')
INSERT INTO modules (name) VALUES ('Tworzenie podcastów Od pomysłu do realizacji')
INSERT INTO modules (name) VALUES ('Jak efektywnie wykorzystać Google Ads')
INSERT INTO modules (name) VALUES ('Sprzedaż B2B skuteczne strategie na zdobycie klienta biznesowego')
INSERT INTO modules (name) VALUES ('Jak rozwijać kreatywność na co dzień')
INSERT INTO modules (name) VALUES ('Zrównoważony styl życia od czego zacząć')
INSERT INTO modules (name) VALUES ('Czas na zmiany Jak wyjść ze strefy komfortu')
INSERT INTO modules (name) VALUES ('Podróżowanie z dziećmi porady dla początkujących')
INSERT INTO modules (name) VALUES ('Recykling w praktyce co naprawdę działa')
INSERT INTO modules (name) VALUES ('Minimalizm w praktyce Jak uprościć swoje życie')
INSERT INTO modules (name) VALUES ('Permakultura jak zaprojektować własny ogród ekologiczny')
INSERT INTO modules (name) VALUES ('Jak wspierać dziecko w nauce')
