INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Kreatywne pomysły na spędzanie czasu z rodziną',1,1)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Jak lepiej zarządzać swoim czasem',2,2)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Jak tworzyć kampanie reklamowe które przyciągają klientów',3,3)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Planowanie budżetu domowego prosty przewodnik',4,4)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Od porażki do sukcesu lekcje które zmieniają życie',5,5)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Jak znaleźć swoją pasję i żyć pełnią życia',6,6)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Social Media Marketing Jak zwiększyć zasięgi organiczne',7,7)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Content marketing od pomysłu do publikacji',8,8)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Sztuka małych kroków jak wprowadzać zmiany na lepsze',9,9)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Zrównoważony rozwój w biznesie Od wizji do działania',10,10)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Jak być szczęśliwym na co dzień',11,11)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Kreatywność w biznesie Jak przełamać schematy myślenia',12,12)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Sztuka pisania jak stworzyć pierwszą książkę',13,13)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Fotografia dla początkujących Od teorii do praktyki',14,14)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Podróż w głąb siebie odkrywanie swoich wartości',15,15)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Zero waste praktyczne porady na start',16,16)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Inspiracja w codziennym życiu jak znaleźć swoje źródło pomysłów',17,17)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Miasta przyszłości Jak będą wyglądać za 51 lat',18,18)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Równowaga między pracą a rodziną Czy to możliwe',19,19)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Historie sukcesu które inspirują do działania',20,20)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Jak ograniczyć ślad węglowy w codziennym życiu',21,21)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Analiza danych marketingowych jak podejmować lepsze decyzje',22,22)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Pokonaj swoje lęki i osiągnij więcej',23,23)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Odnawialne źródła energii jak wykorzystać je w domu',24,24)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Efektywne sposoby na organizację rodzinnego życia',25,25)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'DIY Jak tworzyć własne dekoracje i oszczędzać pieniądze',26,26)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Tworzenie atrakcyjnych ofert sprzedażowych',27,27)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Podstawy rysunku jak zacząć swoją przygodę ze sztuką',28,28)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Email marketing który sprzedaje praktyczne wskazówki',29,29)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Jak wychować pewne siebie dziecko',30,30)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Marzenia a cele jak przekształcić pragnienia w rzeczywistość',31,31)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Storytelling wizualny Jak tworzyć opowieści obrazem',32,32)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'SEO w pigułce jak zwiększyć widoczność swojej strony',33,33)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Jak edukować dzieci o ochronie środowiska',34,34)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Budowanie zaangażowanej społeczności online',35,35)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Moda ekologiczna jak wybierać odpowiedzialnie',36,36)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Jak zaprojektować idealne wnętrze swojego domu',37,37)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Nowoczesne technologie wspierające ekologię',38,38)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Tworzenie muzyki Prosty przewodnik dla początkujących',39,39)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Tworzenie podcastów Od pomysłu do realizacji',40,40)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Jak efektywnie wykorzystać Google Ads',41,41)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Sprzedaż B3B skuteczne strategie na zdobycie klienta biznesowego',42,42)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Jak rozwijać kreatywność na co dzień',43,43)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Zrównoważony styl życia od czego zacząć',44,44)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Czas na zmiany Jak wyjść ze strefy komfortu',45,45)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Podróżowanie z dziećmi porady dla początkujących',46,46)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Recykling w praktyce co naprawdę działa',47,47)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Minimalizm w praktyce Jak uprościć swoje życie',48,48)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Permakultura jak zaprojektować własny ogród ekologiczny',49,49)
INSERT INTO webinars (name,webinarID,moduleID) VALUES (N'Jak wspierać dziecko w nauce',50,50)
